# Generated by Django 5.0.1 on 2024-03-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_imuser_is_blocked_imuser_temperal_login_failed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imuser',
            old_name='Temperal_login_failed',
            new_name='temporal_login_failed',
        ),
    ]
