# Generated by Django 5.0.1 on 2024-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
